local opts = {
  ensure_installed = {
    "gopls",
    "golines",
    "delve",
    "lua-language-server",
    "csharp-language-server",
    "bash-language-server",
    "shellcheck",
    "shellharden",
    "shfmt",
    "pyright",
    "mypy",
    "ruff",
    "black",
    "debugpy",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "hadolint",
    "eslint-lsp",
    "typescript-language-server",
    "deno",
    "quick-lint-js",
    "xo",
    "vue-language-server",
    "jdtls",
    "rnix-lsp",
    "protolint",
    "buf",
    "buf-language-server",
    "sqlls",
    "json-lsp",
  }
}

return opts
